cargo-features = ["profile-overrides"]
edition = 2018

[workspace]
members = [
    "test-crate",
    "transgress-abi",
    "api-scrape",
    "unthwart",
    "prefab",
]

[profile.dev]
opt-level = 2

[profile.dev.overrides."*"]
opt-level = 2