cargo-features = ["profile-overrides"]

[workspace]
members = [
    "test-crate",
    "transgress-abi",
    "analysis-to-transgress",
    "unthwart",
    "prefab",
]

[profile.dev]
opt-level = 2

[profile.dev.overrides."*"]
opt-level = 2