cargo-features = ["profile-overrides"]

[workspace]
members = [
    "test-crate",
    "transgress",
    "transgress-api",
    "transgress-resolve",
    "prefab",
    "spoor"
]

[profile.dev.overrides."*"]
opt-level = 2
