cargo-features = ["profile-overrides"]
[workspace]
members = [
    "test-crate",
    "tendon",
    "tendon-api",
    "tendon-resolve",
    "spoor"
]

[profile.release]
debug = true

[profile.dev.overrides."*"]
opt-level = 2
