[package]
name = "spoor"
version = "0.1.0"
authors = ["James Gilles <jhgilles@mit.edu>"]
edition = "2018"
readme = "README.md"
publish = false

[dependencies]
tracing = "0.1.12"
tracing-subscriber = "0.2.1"
