[package]
name = "test-crate"
publish = false
version = "0.1.0"
authors = ["James Gilles <jhgilles@mit.edu>"]
edition = "2018"

[dependencies]
rand_chacha = "0.1.1"
rand = { version = "0.6", features = ["log"]}